name: 'dbt_data_quality_validation'
version: '1.0'
profile: 'dbt_demo'
config-version: 2

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]

models:
  dbt_data_quality_demo:
    staging:
      +materialized: view
    marts:
      +materialized: table
